<ChangePasswordScreen>

    MDBoxLayout:
        orientation: "vertical"
        md_bg_color: "#F0F1E0"
        padding: "20dp"
        spacing: "15dp"

        MDTopAppBar:
            type: "small"

            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: "arrow-left"
                    on_release:
                        app.root.current = "settings"

            MDTopAppBarTitle:
                text: "Change Password"

        MDTextField:
            id: old_password
            mode: "outlined"

            MDTextFieldHintText:
                text: "Current Password"

        MDTextField:
            id: new_password
            mode: "outlined"

            MDTextFieldHintText:
                text: "New Password"

        MDTextField:
            id: confirm_password
            mode: "outlined"

            MDTextFieldHintText:
                text: "Confirm New Password"

        Widget:

        MDButton:
            style: "filled"
            pos_hint: {"center_x": .5}

            on_release:
                root.change_password()

            MDButtonText:
                text: "Save Password"