<SplashScreen>:

    MDBoxLayout:
        orientation: "vertical"
        spacing: "15dp"
        padding: "35dp"
        md_bg_color: "#f0f1e0"

        Widget:

        MDIcon:
            icon: "sprout"
            size_hint: None, None
            size: "110dp", "110dp"
            pos_hint: {"center_x": 0.5}
            theme_text_color: "Custom"
            text_color: "#0bb229"
            font_size: "90sp"

        MDLabel:
            text: "NovaLedger"
            halign: "center"
            font_style: "Headline"

            theme_text_color: "Custom"
            text_color: "#455a4e"

        MDLabel:
            text: "Smart Expense Tracker"
            halign: "center"

            theme_text_color: "Custom"
            text_color: "#647f6f"

        Widget:
            size_hint_y: .05

        MDLabel:
            text: "Loading..."
            halign: "center"

            theme_text_color: "Custom"
            text_color: "#7ff093"

        Widget: