name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NovaLedger-APK
          path: bin/*.apk
